DECLARE @PuneId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@PuneId, 'Pune');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @PuneId, 'Kothrud'), (NEWID(), @PuneId, 'Viman Nagar'), (NEWID(), @PuneId, 'Hinjewadi'), (NEWID(), @PuneId, 'Kharadi'), (NEWID(), @PuneId, 'Wakad'), (NEWID(), @PuneId, 'Baner'), (NEWID(), @PuneId, 'Aundh'), (NEWID(), @PuneId, 'Magarpatta'), (NEWID(), @PuneId, 'Hadapsar'), (NEWID(), @PuneId, 'Koregaon Park'), (NEWID(), @PuneId, 'Kalyani Nagar'), (NEWID(), @PuneId, 'Shivaji Nagar'), (NEWID(), @PuneId, 'Swargate'), (NEWID(), @PuneId, 'Pimpri'), (NEWID(), @PuneId, 'Chinchwad'), (NEWID(), @PuneId, 'Camp'), (NEWID(), @PuneId, 'Deccan Gymkhana'), (NEWID(), @PuneId, 'Kondhwa'), (NEWID(), @PuneId, 'Katraj'), (NEWID(), @PuneId, 'Vishrantwadi'), (NEWID(), @PuneId, 'Bavdhan'), (NEWID(), @PuneId, 'Pashan'), (NEWID(), @PuneId, 'Balewadi'), (NEWID(), @PuneId, 'Erandwane'), (NEWID(), @PuneId, 'Fatima Nagar'), (NEWID(), @PuneId, 'Nigdi'), (NEWID(), @PuneId, 'Pimple Saudagar'), (NEWID(), @PuneId, 'Pimple Nilakh'), (NEWID(), @PuneId, 'Pimple Gurav'), (NEWID(), @PuneId, 'Thergaon'), (NEWID(), @PuneId, 'Ravet'), (NEWID(), @PuneId, 'Tathawade'), (NEWID(), @PuneId, 'Narhe'), (NEWID(), @PuneId, 'Dhayari'), (NEWID(), @PuneId, 'Sinhagad Road'), (NEWID(), @PuneId, 'Karve Nagar'), (NEWID(), @PuneId, 'Warje');

DECLARE @MumbaiId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@MumbaiId, 'Mumbai');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @MumbaiId, 'Andheri'), (NEWID(), @MumbaiId, 'Bandra'), (NEWID(), @MumbaiId, 'Juhu'), (NEWID(), @MumbaiId, 'Colaba'), (NEWID(), @MumbaiId, 'Malabar Hill'), (NEWID(), @MumbaiId, 'Powai'), (NEWID(), @MumbaiId, 'Borivali'), (NEWID(), @MumbaiId, 'Goregaon'), (NEWID(), @MumbaiId, 'Malad'), (NEWID(), @MumbaiId, 'Kandivali'), (NEWID(), @MumbaiId, 'Dadar'), (NEWID(), @MumbaiId, 'Worli'), (NEWID(), @MumbaiId, 'Lower Parel'), (NEWID(), @MumbaiId, 'South Mumbai'), (NEWID(), @MumbaiId, 'Navi Mumbai'), (NEWID(), @MumbaiId, 'Vashi'), (NEWID(), @MumbaiId, 'Thane'), (NEWID(), @MumbaiId, 'Chembur'), (NEWID(), @MumbaiId, 'Ghatkopar'), (NEWID(), @MumbaiId, 'Kurla'), (NEWID(), @MumbaiId, 'Vile Parle'), (NEWID(), @MumbaiId, 'Santacruz'), (NEWID(), @MumbaiId, 'Khar'), (NEWID(), @MumbaiId, 'Sion'), (NEWID(), @MumbaiId, 'Matunga'), (NEWID(), @MumbaiId, 'Mahim'), (NEWID(), @MumbaiId, 'Prabhadevi'), (NEWID(), @MumbaiId, 'Byculla'), (NEWID(), @MumbaiId, 'Marine Drive'), (NEWID(), @MumbaiId, 'Nariman Point'), (NEWID(), @MumbaiId, 'Fort'), (NEWID(), @MumbaiId, 'Churchgate'), (NEWID(), @MumbaiId, 'Cuffe Parade'), (NEWID(), @MumbaiId, 'Mulund'), (NEWID(), @MumbaiId, 'Bhandup'), (NEWID(), @MumbaiId, 'Vikhroli'), (NEWID(), @MumbaiId, 'Kanjurmarg');

DECLARE @HyderabadId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@HyderabadId, 'Hyderabad');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @HyderabadId, 'Banjara Hills'), (NEWID(), @HyderabadId, 'Jubilee Hills'), (NEWID(), @HyderabadId, 'HITEC City'), (NEWID(), @HyderabadId, 'Madhapur'), (NEWID(), @HyderabadId, 'Gachibowli'), (NEWID(), @HyderabadId, 'Kondapur'), (NEWID(), @HyderabadId, 'Kukatpally'), (NEWID(), @HyderabadId, 'Miyapur'), (NEWID(), @HyderabadId, 'Ameerpet'), (NEWID(), @HyderabadId, 'SR Nagar'), (NEWID(), @HyderabadId, 'Begumpet'), (NEWID(), @HyderabadId, 'Secunderabad'), (NEWID(), @HyderabadId, 'Tarnaka'), (NEWID(), @HyderabadId, 'Uppal'), (NEWID(), @HyderabadId, 'Dilsukhnagar'), (NEWID(), @HyderabadId, 'LB Nagar'), (NEWID(), @HyderabadId, 'Charminar'), (NEWID(), @HyderabadId, 'Mehdipatnam'), (NEWID(), @HyderabadId, 'Tolichowki'), (NEWID(), @HyderabadId, 'Manikonda'), (NEWID(), @HyderabadId, 'Nanakramguda'), (NEWID(), @HyderabadId, 'Somajiguda'), (NEWID(), @HyderabadId, 'Panjagutta'), (NEWID(), @HyderabadId, 'Khairatabad'), (NEWID(), @HyderabadId, 'Abids'), (NEWID(), @HyderabadId, 'Koti'), (NEWID(), @HyderabadId, 'Himayatnagar'), (NEWID(), @HyderabadId, 'Kachiguda'), (NEWID(), @HyderabadId, 'Nampally');

DECLARE @BangaloreId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@BangaloreId, 'Bangalore');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @BangaloreId, 'Koramangala'), (NEWID(), @BangaloreId, 'Indiranagar'), (NEWID(), @BangaloreId, 'Jayanagar'), (NEWID(), @BangaloreId, 'JP Nagar'), (NEWID(), @BangaloreId, 'BTM Layout'), (NEWID(), @BangaloreId, 'HSR Layout'), (NEWID(), @BangaloreId, 'Whitefield'), (NEWID(), @BangaloreId, 'Electronic City'), (NEWID(), @BangaloreId, 'Marathahalli'), (NEWID(), @BangaloreId, 'Bellandur'), (NEWID(), @BangaloreId, 'Sarjapur Road'), (NEWID(), @BangaloreId, 'Outer Ring Road'), (NEWID(), @BangaloreId, 'Hebbal'), (NEWID(), @BangaloreId, 'Yelahanka'), (NEWID(), @BangaloreId, 'Malleshwaram'), (NEWID(), @BangaloreId, 'Rajajinagar'), (NEWID(), @BangaloreId, 'Basavanagudi'), (NEWID(), @BangaloreId, 'Frazer Town'), (NEWID(), @BangaloreId, 'Cox Town'), (NEWID(), @BangaloreId, 'Cooke Town'), (NEWID(), @BangaloreId, 'Kammanahalli'), (NEWID(), @BangaloreId, 'Banaswadi'), (NEWID(), @BangaloreId, 'KR Puram'), (NEWID(), @BangaloreId, 'CV Raman Nagar'), (NEWID(), @BangaloreId, 'Mahadevapura'), (NEWID(), @BangaloreId, 'Brookefield'), (NEWID(), @BangaloreId, 'Kundalahalli'), (NEWID(), @BangaloreId, 'Doddanekundi'), (NEWID(), @BangaloreId, 'RT Nagar'), (NEWID(), @BangaloreId, 'Sanjaynagar');

DECLARE @SolapurId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@SolapurId, 'Solapur');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @SolapurId, 'Navi Peth'), (NEWID(), @SolapurId, 'Sadar Bazar'), (NEWID(), @SolapurId, 'Hotgi Road'), (NEWID(), @SolapurId, 'Jule Solapur'), (NEWID(), @SolapurId, 'Ashok Chowk'), (NEWID(), @SolapurId, 'Saat Rasta'), (NEWID(), @SolapurId, 'MIDC'), (NEWID(), @SolapurId, 'Majrewadi'), (NEWID(), @SolapurId, 'Dufferin Chowk'), (NEWID(), @SolapurId, 'Balives'), (NEWID(), @SolapurId, 'Bhavani Peth'), (NEWID(), @SolapurId, 'Gold Finch Peth'), (NEWID(), @SolapurId, 'Sakhar Peth'), (NEWID(), @SolapurId, 'South Kasba'), (NEWID(), @SolapurId, 'North Kasba'), (NEWID(), @SolapurId, 'Soregaon'), (NEWID(), @SolapurId, 'Kumthe'), (NEWID(), @SolapurId, 'Akkalkot Road'), (NEWID(), @SolapurId, 'Vijapur Road'), (NEWID(), @SolapurId, 'Railway Station Area');

DECLARE @DelhiId UNIQUEIDENTIFIER = NEWID();
INSERT INTO Cities (Id, Name) VALUES (@DelhiId, 'Delhi');
INSERT INTO Localities (Id, CityId, Name) VALUES (NEWID(), @DelhiId, 'Connaught Place'), (NEWID(), @DelhiId, 'Karol Bagh'), (NEWID(), @DelhiId, 'Paharganj'), (NEWID(), @DelhiId, 'Chandni Chowk'), (NEWID(), @DelhiId, 'Chawri Bazar'), (NEWID(), @DelhiId, 'Daryaganj'), (NEWID(), @DelhiId, 'Pitampura'), (NEWID(), @DelhiId, 'Rohini'), (NEWID(), @DelhiId, 'Shalimar Bagh'), (NEWID(), @DelhiId, 'Model Town'), (NEWID(), @DelhiId, 'Civil Lines'), (NEWID(), @DelhiId, 'Kamla Nagar'), (NEWID(), @DelhiId, 'Mukherjee Nagar'), (NEWID(), @DelhiId, 'GTB Nagar'), (NEWID(), @DelhiId, 'Rajouri Garden'), (NEWID(), @DelhiId, 'Punjabi Bagh'), (NEWID(), @DelhiId, 'Paschim Vihar'), (NEWID(), @DelhiId, 'Janakpuri'), (NEWID(), @DelhiId, 'Dwarka'), (NEWID(), @DelhiId, 'Vasant Kunj'), (NEWID(), @DelhiId, 'Vasant Vihar'), (NEWID(), @DelhiId, 'Hauz Khas'), (NEWID(), @DelhiId, 'Green Park'), (NEWID(), @DelhiId, 'South Extension'), (NEWID(), @DelhiId, 'Defence Colony'), (NEWID(), @DelhiId, 'Lajpat Nagar'), (NEWID(), @DelhiId, 'Greater Kailash'), (NEWID(), @DelhiId, 'Saket'), (NEWID(), @DelhiId, 'Malviya Nagar'), (NEWID(), @DelhiId, 'Chhatarpur'), (NEWID(), @DelhiId, 'Laxmi Nagar'), (NEWID(), @DelhiId, 'Preet Vihar'), (NEWID(), @DelhiId, 'Mayur Vihar'), (NEWID(), @DelhiId, 'Patparganj'), (NEWID(), @DelhiId, 'Shahdara'), (NEWID(), @DelhiId, 'Anand Vihar');
